# Generated by Django 4.0.4 on 2022-05-01 00:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon', models.ImageField(upload_to='icons')),
                ('description', models.TextField(max_length=1000)),
                ('category', models.CharField(choices=[('Analises', 'Análises'), ('Programacao', 'Programação'), ('Apresentacao', 'Apresentação'), ('Outros', 'Outros')], max_length=15)),
                ('views', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
