# Generated by Django 4.0.4 on 2022-05-01 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video', models.URLField()),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='serie.serie')),
            ],
        ),
    ]
